### PR TITLE
Refine flash messaging

### PR DESCRIPTION
**Pull request by jf**
Please note that this builds on PR #28

### CODE REVIEW

**Comment by Quintasan** [comment]
Please include a default message so I that the users get something rather than an empty string.

**Comment by jf** [comment]
:) I've got my stuff set up where if the message is blank, it actually doesn't show the message; but I can see how that might be confusing otherwise (the flash is shown, but there's no text in there).

So in the light of that, I was going with not showing any message at all, my thinking being that the context (you just tried to do something which is protected, like say viewing your user profile), + the actual showing of the login page should make things clear.

So I guess there are 2 approaches/resolutions here:
1. make the default message nil instead (so that no message is shown)
2. show some other default message

What are your thoughts on this?

**Comment by Quintasan** [comment]
I'm of the opinion that if you are redirecting the user to the login page you should make it clear why did that redirect happen. Just displaying the login page can be confusing. I'd opt for the 2nd option with a "This action requires that you log in." or something along these lines.

**Comment by jf** [comment]
Ok, I wil put in an appropriate message.

**Pull request merged**
